/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.Conexao;
import java.awt.event.FocusListener;
import javax.swing.JOptionPane;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.Arrays;
import javax.swing.Icon;
import javax.swing.JFrame;
import model.Historico;
/**
 *
 * @author anrde
 */

public class Calculadora extends javax.swing.JFrame {
    private java.awt.event.ActionEvent evt1;
    
    float[] vt = new float[10];
    boolean teste = false;
    String sinal;
    boolean acao = false;
    DecimalFormat df = new DecimalFormat();
    Historico historico = new Historico();
    float calculo = 0;
    float rodada = 0;
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        
        setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
        
    vt[0] = 0f;
    vt[1] = 0f;
    vt[2] = 0f;
    vt[3] = 0f;
    vt[4] = 0f;
    vt[5] = 0f;
    vt[6] = 0f;
    vt[7] = 0f;
    vt[8] = 0f;
    vt[9] = 0f;
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        btn1 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        TxtResultado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn6 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnAdicao = new javax.swing.JButton();
        btnSubtracao = new javax.swing.JButton();
        btnDivisao = new javax.swing.JButton();
        btnMultiplicacao = new javax.swing.JButton();
        btnVirgula = new javax.swing.JButton();
        btnApagarCE = new javax.swing.JButton();
        btnApagarC = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Anderson");
        setAlwaysOnTop(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        btn1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn1.setText("1");
        btn1.setMaximumSize(new java.awt.Dimension(75, 22));
        btn1.setMinimumSize(new java.awt.Dimension(75, 22));
        btn1.setPreferredSize(new java.awt.Dimension(75, 22));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn7.setText("7");
        btn7.setMaximumSize(new java.awt.Dimension(75, 22));
        btn7.setMinimumSize(new java.awt.Dimension(75, 22));
        btn7.setPreferredSize(new java.awt.Dimension(75, 22));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn4.setText("4");
        btn4.setMaximumSize(new java.awt.Dimension(75, 22));
        btn4.setMinimumSize(new java.awt.Dimension(75, 22));
        btn4.setPreferredSize(new java.awt.Dimension(75, 22));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn5.setText("5");
        btn5.setMaximumSize(new java.awt.Dimension(75, 22));
        btn5.setMinimumSize(new java.awt.Dimension(75, 22));
        btn5.setPreferredSize(new java.awt.Dimension(75, 22));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn0.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn0.setText("0");
        btn0.setMaximumSize(new java.awt.Dimension(75, 22));
        btn0.setMinimumSize(new java.awt.Dimension(75, 22));
        btn0.setPreferredSize(new java.awt.Dimension(75, 22));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        btn0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn0KeyPressed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn9.setText("9");
        btn9.setMaximumSize(new java.awt.Dimension(75, 22));
        btn9.setMinimumSize(new java.awt.Dimension(75, 22));
        btn9.setPreferredSize(new java.awt.Dimension(75, 22));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel9.setForeground(new java.awt.Color(204, 204, 204));
        jPanel9.setAutoscrolls(true);

        TxtResultado.setEditable(false);
        TxtResultado.setBackground(new java.awt.Color(204, 204, 204));
        TxtResultado.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        TxtResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtResultadoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("    Calculadora Anderson");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtResultado)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn6.setText("6");
        btn6.setMaximumSize(new java.awt.Dimension(75, 22));
        btn6.setMinimumSize(new java.awt.Dimension(75, 22));
        btn6.setPreferredSize(new java.awt.Dimension(75, 22));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn2.setText("2");
        btn2.setMaximumSize(new java.awt.Dimension(75, 22));
        btn2.setMinimumSize(new java.awt.Dimension(75, 22));
        btn2.setPreferredSize(new java.awt.Dimension(75, 22));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn8.setText("8");
        btn8.setMaximumSize(new java.awt.Dimension(75, 22));
        btn8.setMinimumSize(new java.awt.Dimension(75, 22));
        btn8.setPreferredSize(new java.awt.Dimension(75, 22));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn3.setText("3");
        btn3.setMaximumSize(new java.awt.Dimension(75, 22));
        btn3.setMinimumSize(new java.awt.Dimension(75, 22));
        btn3.setPreferredSize(new java.awt.Dimension(75, 22));
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        btn3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btn3KeyTyped(evt);
            }
        });

        btnIgual.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnIgual.setText("=");
        btnIgual.setMaximumSize(new java.awt.Dimension(75, 22));
        btnIgual.setMinimumSize(new java.awt.Dimension(75, 22));
        btnIgual.setPreferredSize(new java.awt.Dimension(75, 22));
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnAdicao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAdicao.setText("+");
        btnAdicao.setMaximumSize(new java.awt.Dimension(75, 22));
        btnAdicao.setMinimumSize(new java.awt.Dimension(75, 22));
        btnAdicao.setPreferredSize(new java.awt.Dimension(75, 22));
        btnAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicaoActionPerformed(evt);
            }
        });

        btnSubtracao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSubtracao.setText("-");
        btnSubtracao.setMaximumSize(new java.awt.Dimension(75, 22));
        btnSubtracao.setMinimumSize(new java.awt.Dimension(75, 22));
        btnSubtracao.setPreferredSize(new java.awt.Dimension(75, 22));
        btnSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtracaoActionPerformed(evt);
            }
        });

        btnDivisao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnDivisao.setText("÷");
        btnDivisao.setMaximumSize(new java.awt.Dimension(75, 22));
        btnDivisao.setMinimumSize(new java.awt.Dimension(75, 22));
        btnDivisao.setPreferredSize(new java.awt.Dimension(75, 22));
        btnDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisaoActionPerformed(evt);
            }
        });

        btnMultiplicacao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMultiplicacao.setText("×");
        btnMultiplicacao.setMaximumSize(new java.awt.Dimension(75, 22));
        btnMultiplicacao.setMinimumSize(new java.awt.Dimension(75, 22));
        btnMultiplicacao.setPreferredSize(new java.awt.Dimension(75, 22));
        btnMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacaoActionPerformed(evt);
            }
        });

        btnVirgula.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnVirgula.setText(",");
        btnVirgula.setMaximumSize(new java.awt.Dimension(75, 22));
        btnVirgula.setMinimumSize(new java.awt.Dimension(75, 22));
        btnVirgula.setPreferredSize(new java.awt.Dimension(75, 22));
        btnVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVirgulaActionPerformed(evt);
            }
        });

        btnApagarCE.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnApagarCE.setText("CE");
        btnApagarCE.setMaximumSize(new java.awt.Dimension(75, 22));
        btnApagarCE.setMinimumSize(new java.awt.Dimension(75, 22));
        btnApagarCE.setPreferredSize(new java.awt.Dimension(75, 22));
        btnApagarCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarCEActionPerformed(evt);
            }
        });

        btnApagarC.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnApagarC.setText("C");
        btnApagarC.setMaximumSize(new java.awt.Dimension(75, 22));
        btnApagarC.setMinimumSize(new java.awt.Dimension(75, 22));
        btnApagarC.setPreferredSize(new java.awt.Dimension(75, 22));
        btnApagarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnApagarCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnApagarC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApagarCE, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApagarC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApagarCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarCEActionPerformed
        TxtResultado.setText("");
    }//GEN-LAST:event_btnApagarCEActionPerformed

    private void btnApagarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarCActionPerformed
        TxtResultado.setText("");
        vt[0] = 0f;
        vt[1] = 0f;
        vt[2] = 0f;
        vt[3] = 0f;
        vt[4] = 0f;
        vt[5] = 0f;
        vt[6] = 0f;
        vt[7] = 0f;
        vt[8] = 0f;
        vt[9] = 0f;
        rodada = 0;
    }//GEN-LAST:event_btnApagarCActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        TxtResultado.setText(TxtResultado.getText() + "1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        TxtResultado.setText(TxtResultado.getText() + "2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        TxtResultado.setText(TxtResultado.getText() + "4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        TxtResultado.setText(TxtResultado.getText() + "5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        TxtResultado.setText(TxtResultado.getText() + "6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        TxtResultado.setText(TxtResultado.getText() + "7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        TxtResultado.setText(TxtResultado.getText() + "8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        TxtResultado.setText(TxtResultado.getText() + "9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicaoActionPerformed
            
        
        historico.setPriNum(TxtResultado.getText() + " + ");
        
        
            if(vt[8] != 0){
                vt[9] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                TxtResultado.setText("");
             }else if(vt[7] != 0){
                vt[8] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                TxtResultado.setText("");
             }else if(vt[6] != 0){
                    vt[7] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }else if(vt[5] != 0){
                    vt[6] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }else if(vt[4] != 0){
                    vt[5] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }else if(vt[3] != 0){
                    vt[4] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }else if(vt[2] != 0){
                    vt[3] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }else if(vt[1] != 0){
                    vt[2] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }else if(vt[0] != 0){
                    vt[1] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }
            
                if(vt[0] == 0){
                 vt[0] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                TxtResultado.setText("");
                }
            
        
        
        
       
            
        /*Arrays.sort(vt);
            for(int i = 0; i < 10; i++){
                if(vt[i] == 0){
                    vt[i] = Float.valueOf(TxtResultado.getText());
                    TxtResultado.setText("");
                }
                break;
            }*/
        
        /*
        for(int i = 0; i < 10; i++){
        System.out.println(vt[i]);
        }
        System.out.println("________________________________________");
        
    if(vt[1] != 0f || vt[2] != 0f || vt[3] != 0f || vt[4] != 0f){
       rodada = vt[0] + vt[1]+ vt[2]+ vt[3]+ vt[4]+ vt[5]+ vt[6]+ vt[7]+ vt[8]+ vt[9];
            
           historico.setSomaTotal(String.valueOf(rodada));
            
                  
        vt[0] = 0f;
        vt[1] = 0f;
        vt[2] = 0f;
        vt[3] = 0f;
        vt[4] = 0f;
        vt[5] = 0f;
        vt[6] = 0f;
        vt[7] = 0f;
        vt[8] = 0f;
        vt[9] = 0f;  
        System.out.println("Soma total: "+historico.getSomaTotal());
        }*/
        sinal = "+";
        
    }//GEN-LAST:event_btnAdicaoActionPerformed

    private void btnVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVirgulaActionPerformed
        TxtResultado.setText(TxtResultado.getText()+",");
    }//GEN-LAST:event_btnVirgulaActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        historico.setSegunNum(TxtResultado.getText());
         
        try{
            vt[9] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
        
        if(sinal.equals("+")){
            calculo = vt[0] + vt[1]+ vt[2]+ vt[3]+ vt[4]+ vt[5]+ vt[6]+ vt[7]+ vt[8]+ vt[9];
            
            TxtResultado.setText(String.valueOf(df.format(calculo)));
        
        vt[0] = 0f;
        vt[1] = 0f;
        vt[2] = 0f;
        vt[3] = 0f;
        vt[4] = 0f;
        vt[5] = 0f;
        vt[6] = 0f;
        vt[7] = 0f;
        vt[8] = 0f;
        vt[9] = 0f;          
        }
        
        if(sinal.equals("-")){
            calculo = vt[0] - vt[1] - vt[2] - vt[3] - vt[4] - vt[5] - vt[6] - vt[7] - vt[8] - vt[9];
            
            TxtResultado.setText(String.valueOf(df.format(calculo)));
        
        vt[0] = 0f;
        vt[1] = 0f;
        vt[2] = 0f;
        vt[3] = 0f;
        vt[4] = 0f;
        vt[5] = 0f;
        vt[6] = 0f;
        vt[7] = 0f;
        vt[8] = 0f;
        vt[9] = 0f;          
        }
        
        if(sinal.equals("X")){
             if(vt[0] != 0 && vt[1] != 0 && vt[2] != 0 && vt[3] != 0 && vt[4] 
                    != 0 && vt[5] != 0 &&vt[6] != 0 && vt[7] != 0 && vt[8] != 0 && vt[9] != 0){
                calculo = vt[0] * vt[1] * vt[2] * vt[3] * vt[4] * vt[5] * vt[6] * vt[7] * vt[8] * vt[9];
            }else if(vt[0] != 0 && vt[1] != 0 && vt[2] != 0 && vt[3] != 0 && vt[4] 
                    != 0 && vt[5] != 0 &&vt[6] != 0 && vt[7] != 0 && vt[9] != 0){
                calculo = vt[0] * vt[1] * vt[2] * vt[3] * vt[4] * vt[5] * vt[6] * vt[7] * vt[9];
            }else if(vt[0] != 0 && vt[1] != 0 && vt[2] != 0 && vt[3] != 0 && vt[4] 
                    != 0 && vt[5] != 0 &&vt[6] != 0 && vt[9] != 0){
                calculo = vt[0] * vt[1] * vt[2] * vt[3] * vt[4] * vt[5] * vt[6] * vt[9];
            }else if(vt[0] != 0 && vt[1] != 0 && vt[2] != 0 && vt[3] != 0 && vt[4] 
                    != 0 && vt[5] != 0 && vt[9] != 0){
                calculo = vt[0] * vt[1] * vt[2] * vt[3] * vt[4] * vt[5] * vt[9];
            }else if(vt[0] != 0 && vt[1] != 0 && vt[2] != 0 && vt[3] != 0 && vt[4] 
                    != 0 && vt[9] != 0){
                calculo = vt[0] * vt[1] * vt[2] * vt[3] * vt[4] * vt[9];
            }else if(vt[0] != 0 && vt[1] != 0 && vt[2] != 0 && vt[3] != 0 && vt[9] != 0){
                calculo = vt[0] * vt[1] * vt[2] * vt[3] * vt[9];
            }else if(vt[0] != 0 && vt[1] != 0 && vt[2] != 0 && vt[9] != 0){
                calculo = vt[0] * vt[1] * vt[2] * vt[9];
            }else if(vt[0] != 0 && vt[1] != 0 && vt[9] != 0){
                calculo = vt[0] * vt[1] * vt[9];
            }else if(vt[0] != 0 && vt[9] != 0){
                calculo = vt[0] * vt[9];
            }
             TxtResultado.setText(String.valueOf(df.format(calculo)));
        vt[0] = 0f;
        vt[1] = 0f;
        vt[2] = 0f;
        vt[3] = 0f;
        vt[4] = 0f;
        vt[5] = 0f;
        vt[6] = 0f;
        vt[7] = 0f;
        vt[8] = 0f;
        vt[9] = 0f;          
        }
        
        if(sinal.equals("/")){
             if(vt[0] != 0 && vt[1] != 0 && vt[2] != 0 && vt[3] != 0 && vt[4] 
                    != 0 && vt[5] != 0 &&vt[6] != 0 && vt[7] != 0 && vt[8] != 0 && vt[9] != 0){
                calculo = vt[0] / vt[1] / vt[2] / vt[3] / vt[4] / vt[5] / vt[6] / vt[7] / vt[8] / vt[9];
            }else if(vt[0] != 0 && vt[1] != 0 && vt[2] != 0 && vt[3] != 0 && vt[4] 
                    != 0 && vt[5] != 0 &&vt[6] != 0 && vt[7] != 0 && vt[9] != 0){
                calculo = vt[0] / vt[1] / vt[2] / vt[3] / vt[4] / vt[5] / vt[6] / vt[7] / vt[9];
            }else if(vt[0] != 0 && vt[1] != 0 && vt[2] != 0 && vt[3] != 0 && vt[4] 
                    != 0 && vt[5] != 0 &&vt[6] != 0 && vt[9] != 0){
                calculo = vt[0] / vt[1] / vt[2] / vt[3] / vt[4] / vt[5] / vt[6] / vt[9];
            }else if(vt[0] != 0 && vt[1] != 0 && vt[2] != 0 && vt[3] != 0 && vt[4] 
                    != 0 && vt[5] != 0 && vt[9] != 0){
                calculo = vt[0] / vt[1] / vt[2] / vt[3] / vt[4] / vt[5] / vt[9];
            }else if(vt[0] != 0 && vt[1] != 0 && vt[2] != 0 && vt[3] != 0 && vt[4] 
                    != 0 && vt[9] != 0){
                calculo = vt[0] / vt[1] / vt[2] / vt[3] / vt[4] / vt[9];
            }else if(vt[0] != 0 && vt[1] != 0 && vt[2] != 0 && vt[3] != 0 && vt[9] != 0){
                calculo = vt[0] / vt[1] / vt[2] / vt[3] / vt[9];
            }else if(vt[0] != 0 && vt[1] != 0 && vt[2] != 0 && vt[9] != 0){
                calculo = vt[0] / vt[1] / vt[2] / vt[9];
            }else if(vt[0] != 0 && vt[1] != 0 && vt[9] != 0){
                calculo = vt[0] / vt[1] / vt[9];
            }else if(vt[0] != 0 && vt[9] != 0){
                calculo = vt[0] / vt[9];
            }
             TxtResultado.setText(String.valueOf(df.format(calculo)));
        vt[0] = 0f;
        vt[1] = 0f;
        vt[2] = 0f;
        vt[3] = 0f;
        vt[4] = 0f;
        vt[5] = 0f;
        vt[6] = 0f;
        vt[7] = 0f;
        vt[8] = 0f;
        vt[9] = 0f;          
        }
        
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Insira um número no campo!");
       }
        
        
        Conexao con = new Conexao();
        
        try{
        
            
        historico.setNumero( TxtResultado.getText() );
        
        TxtResultado.setText(historico.getPriNum() + historico.getSegunNum() + " = " + historico.getNumero());
        
        
        historico.setResultado(TxtResultado.getText());
        
        con.inserir(historico);
        
        
       
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnIgualActionPerformed

        
    
    
    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        //*********************************************************************************
        
        System.out.println(KeyEvent.VK_3);
        
    }//GEN-LAST:event_formKeyPressed

    private void btn3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn3KeyTyped

    }//GEN-LAST:event_btn3KeyTyped

    private void btn3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn3KeyReleased

    }//GEN-LAST:event_btn3KeyReleased

    private void btn3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn3KeyPressed

    }//GEN-LAST:event_btn3KeyPressed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        TxtResultado.setText(TxtResultado.getText()+"3");    
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked

    }//GEN-LAST:event_btn3MouseClicked

    private void btn0KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn0KeyPressed

    }//GEN-LAST:event_btn0KeyPressed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        TxtResultado.setText(TxtResultado.getText()+"0");    
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtracaoActionPerformed
        
        historico.setPriNum(TxtResultado.getText() + " - ");
        System.out.println(historico.getPriNum());
        
        
        if(vt[8] != 0){
                vt[9] = Float.valueOf(TxtResultado.getText());
                TxtResultado.setText("");
             }else if(vt[7] != 0){
                vt[8] = Float.valueOf(TxtResultado.getText());
                TxtResultado.setText("");
             }else if(vt[6] != 0){
                    vt[7] = Float.valueOf(TxtResultado.getText());
                    TxtResultado.setText("");
             }else if(vt[5] != 0){
                    vt[6] = Float.valueOf(TxtResultado.getText());
                    TxtResultado.setText("");
             }else if(vt[4] != 0){
                    vt[5] = Float.valueOf(TxtResultado.getText());
                    TxtResultado.setText("");
             }else if(vt[3] != 0){
                    vt[4] = Float.valueOf(TxtResultado.getText());
                    TxtResultado.setText("");
             }else if(vt[2] != 0){
                    vt[3] = Float.valueOf(TxtResultado.getText());
                    TxtResultado.setText("");
             }else if(vt[1] != 0){
                    vt[2] = Float.valueOf(TxtResultado.getText());
                    TxtResultado.setText("");
             }else if(vt[0] != 0){
                    vt[1] = Float.valueOf(TxtResultado.getText());
                    TxtResultado.setText("");
             }
            
                if(vt[0] == 0){
                 vt[0] = Float.valueOf(TxtResultado.getText());
                TxtResultado.setText("");
                }
            
        sinal = "-";
        
        
    }//GEN-LAST:event_btnSubtracaoActionPerformed

    private void btnDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisaoActionPerformed
            
        historico.setPriNum(TxtResultado.getText() + " ÷ ");
        System.out.println(historico.getPriNum());
        
        
        if(vt[8] != 0){
                vt[9] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                TxtResultado.setText("");
             }else if(vt[7] != 0){
                vt[8] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                TxtResultado.setText("");
             }else if(vt[6] != 0){
                    vt[7] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }else if(vt[5] != 0){
                    vt[6] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }else if(vt[4] != 0){
                    vt[5] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }else if(vt[3] != 0){
                    vt[4] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }else if(vt[2] != 0){
                    vt[3] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }else if(vt[1] != 0){
                    vt[2] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }else if(vt[0] != 0){
                    vt[1] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }
            
                if(vt[0] == 0){
                 vt[0] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                TxtResultado.setText("");
                }
                
            
        sinal = "/";
        
    }//GEN-LAST:event_btnDivisaoActionPerformed

    private void btnMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacaoActionPerformed
            
            historico.setPriNum(TxtResultado.getText() + " × ");
            System.out.println(historico.getPriNum());
        
        if(vt[8] != 0){
                vt[9] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                TxtResultado.setText("");
             }else if(vt[7] != 0){
                vt[8] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                TxtResultado.setText("");
             }else if(vt[6] != 0){
                    vt[7] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }else if(vt[5] != 0){
                    vt[6] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }else if(vt[4] != 0){
                    vt[5] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }else if(vt[3] != 0){
                    vt[4] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }else if(vt[2] != 0){
                    vt[3] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }else if(vt[1] != 0){
                    vt[2] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }else if(vt[0] != 0){
                    vt[1] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                    TxtResultado.setText("");
             }
                if(vt[0] == 0){
                 vt[0] = Float.valueOf(TxtResultado.getText().replaceAll(",", "."));
                TxtResultado.setText("");
                }
        sinal = "X";
    }//GEN-LAST:event_btnMultiplicacaoActionPerformed

    private void TxtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtResultadoActionPerformed

    }//GEN-LAST:event_TxtResultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtResultado;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdicao;
    private javax.swing.JButton btnApagarC;
    private javax.swing.JButton btnApagarCE;
    private javax.swing.JButton btnDivisao;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMultiplicacao;
    private javax.swing.JButton btnSubtracao;
    private javax.swing.JButton btnVirgula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
